name: Release Neoxa Payments Plugin

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Create Release Folder
      run: |
        mkdir -p build/neoxa-payments
        
    - name: Copy Files
      run: |
        cp -r admin build/neoxa-payments/
        cp -r includes build/neoxa-payments/
        cp -r assets build/neoxa-payments/
        cp neoxa-payments.php build/neoxa-payments/
        cp README.md build/neoxa-payments/
        cp LICENSE build/neoxa-payments/
        
    - name: Create ZIP Archive
      run: |
        cd build
        zip -r neoxa-payments.zip neoxa-payments/
        cd ..
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/neoxa-payments.zip
        name: Release ${{ github.ref_name }}
        body: |
          Neoxa Payments WordPress Plugin Release ${{ github.ref_name }}
          
          This release includes:
          - WooCommerce integration for Neoxa payments
          - Support for Neoxa assets
          - Admin interface for configuration
          - Real-time payment verification
          - Automatic order status updates
        draft: false
        prerelease: false
